"""give_away try

Revision ID: 22a3b8201236
Revises: 70197d70e7b5
Create Date: 2023-05-11 14:21:18.002440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a3b8201236'
down_revision = '70197d70e7b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
