"""cls in oldest_company

Revision ID: 295886a7a51f
Revises: 6cc3e65a0d7e
Create Date: 2023-05-11 12:59:39.156913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295886a7a51f'
down_revision = '6cc3e65a0d7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
