"""trying setting Freebie.id

Revision ID: 2bf8ba1d8850
Revises: c712f403afd6
Create Date: 2023-05-11 12:46:32.041625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf8ba1d8850'
down_revision = 'c712f403afd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
