"""fix args

Revision ID: 2c2ff2e7a22f
Revises: 295886a7a51f
Create Date: 2023-05-11 13:37:21.423223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c2ff2e7a22f'
down_revision = '295886a7a51f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
