"""give_away better code

Revision ID: 5fdbfdd88f7f
Revises: 22a3b8201236
Create Date: 2023-05-11 14:26:11.065418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fdbfdd88f7f'
down_revision = '22a3b8201236'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
