"""made oldest_company a class method

Revision ID: 6cc3e65a0d7e
Revises: 79e914f63417
Create Date: 2023-05-11 12:58:09.056455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cc3e65a0d7e'
down_revision = '79e914f63417'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
