"""wrote received_one hope it works

Revision ID: 70197d70e7b5
Revises: 7db381407e3c
Create Date: 2023-05-11 14:14:22.611393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70197d70e7b5'
down_revision = '7db381407e3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
