"""oldest_company

Revision ID: 79e914f63417
Revises: 2bf8ba1d8850
Create Date: 2023-05-11 12:56:41.021847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e914f63417'
down_revision = '2bf8ba1d8850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
