"""received_one try

Revision ID: 7db381407e3c
Revises: 90acc6fbf936
Create Date: 2023-05-11 14:11:34.632909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db381407e3c'
down_revision = '90acc6fbf936'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
