"""altered print_details

Revision ID: 8ca3b0acbfe3
Revises: c371c22f4225
Create Date: 2023-05-11 11:54:20.506360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca3b0acbfe3'
down_revision = 'c371c22f4225'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
