"""update oldest_company

Revision ID: 90acc6fbf936
Revises: da71e1a22656
Create Date: 2023-05-11 13:58:07.825636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90acc6fbf936'
down_revision = 'da71e1a22656'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
