"""give_away added dev.id

Revision ID: aae63ddbde0b
Revises: 5fdbfdd88f7f
Create Date: 2023-05-11 14:28:30.603566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae63ddbde0b'
down_revision = '5fdbfdd88f7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
