"""give_freebie

Revision ID: b335d574067b
Revises: 2c2ff2e7a22f
Create Date: 2023-05-11 13:42:46.336445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b335d574067b'
down_revision = '2c2ff2e7a22f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
