"""add print_details method to Freebie

Revision ID: c371c22f4225
Revises: 4866d9558fde
Create Date: 2023-05-11 11:41:27.792032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c371c22f4225'
down_revision = '4866d9558fde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
