"""Company give_freebie

Revision ID: c712f403afd6
Revises: 52c0650c3daf
Create Date: 2023-05-11 12:35:47.186602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c712f403afd6'
down_revision = '52c0650c3daf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
