"""give_freebie returns instance

Revision ID: da71e1a22656
Revises: b335d574067b
Create Date: 2023-05-11 13:51:56.500350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da71e1a22656'
down_revision = 'b335d574067b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
