"""adjust again

Revision ID: f2fd9cbf71e8
Revises: 8ca3b0acbfe3
Create Date: 2023-05-11 11:56:52.222755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fd9cbf71e8'
down_revision = '8ca3b0acbfe3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
